export{default as Header} from '../sections/Header/Header'
export{default as Hero} from '../sections/Hero/Hero'
export{default as MostPop} from '../sections/MostPop/MostPop'
export{default as GamingLibrary} from '../sections/GamingLibrary/GamingLibrary'
export{default as Footer} from '../sections/Footer/Footer'
